### ISSUE TITLE
Tiny font when running under Java 11.0.1

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#115]
**Describe the bug**
When running VisualVM 1.4.2 under Java 11.0.1 the fonts (and maybe the icons too) look tiny compared to earlier Java versions.

**To Reproduce**
1. Open VisualVM under Java 11.0.1

**Expected behavior**
Text/icons should be easy to read.

**VisualVM log**
[logfile.txt](https://github.com/oracle/visualvm/files/2568953/logfile.txt)

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/633348/48307704-6c179880-e520-11e8-9aa9-3742b3800c8b.jpg)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.55]
 - JDK version: openjdk version "11.0.1" 2018-10-16
 - Version: 1.4.2

**Comment by jisedlac** [comment]
I don't see anything we can do on VisualVM side to make it appear the same way on all JDKs and hardware configurations.

Please use the sun.java2d.uiScale and fontsize parameters to tweak the UI to look best for you.

For example, I use these: `visualvm -J-Dsun.java2d.uiScale=1.0 --fontsize 15`.

**Comment by cowwoc** [comment]
@jisedlac I consider this to be a VisualVM-specific problem because other Java applications I am running do not exhibit any problems. It's quite possible they already corrected this on their end.

I tried both the parameters you mentioned and recommend using `--fontsize 15` exclusively. It seems to correct the problem (works well across two different monitors with different resolutions and scale factors), and works better without `-J-Dsun.java2d.uiScale=1.0`.

Is it possible to add this to the default configuration file?

Also (big picture) is this a JDK bug in that their default font size is incorrect? Is there an existing bug report for this?

**Comment by jisedlac** [comment]
Given that VisualVM looks as designed when using Java 8, any UI problems observed using Java 9+ are caused by changes in Swing. The problem for sure isn't VisualVM specific as it occurs also in NetBeans Platform components. VisualVM itself doesn't perform any special UI tweaks.

We can't add any `fontsize` value as a default because the right value depends on the target OS settings (respecting system font size), DPI, JDK used and - last but not least - user preference. You should just update your `etc/visualvm.conf` file with the `fontsize` value optimal for your configuration to have it persistent.

Could you please be specific on which Java applications use the default LaF and do not exhibit these problems with Java 9+? For example JConsole from Java 11 shows the same problems on my system.

**Comment by cowwoc** [comment]
@jisedlac You're right. Is there an existing JDK bug open against this?

**Comment by jisedlac** [comment]
I'm not aware of any.

**Comment by jisedlac** [comment]
Just for reference - the SwingSet2 demo application shows the same fontsize issues when running using Java 11 and set to the Windows LaF. Seems to be a Windows LaF bug.

**Comment by cowwoc** [comment]
The problem went away by itself, presumably as a result of a Windows update. Closing for now.
