### ISSUE TITLE
Allow skipping ssl check in --openjmx cli 

### ISSUE THREAD

**Issue by queimadus** [oracle/visualvm#2]
Skipping ssl is available when connecting to a remote jmx via the GUI but not via the cli.
Latest release (1.3.9) closes [Issue 618](https://java.net/jira/browse/VISUALVM-618) which addresses this but such feature doesn't seem to be present.

Tracked the [commit](https://github.com/visualvm/visualvm.src/commit/406b443c66d6673d353827ee56e4a0102df81210) pertaining to the issue 618.

**Comment by jisedlac** [comment]
The SSL check is only performed when username & password are provided for a JMX connection. Since the `--openjmx` command doesn't support providing username & password, it also doesn't provide the option to disable SSL check.

I assume you're mentioning the scenario where there's a JMX-enabled process configured with `com.sun.management.jmxremote.authenticate=true` and you want to create the corresponding connection in VisualVM using `--openjmx`.

In this case a dialog pops up in the GUI asking you to provide username & password for the connection, eventually followed by another dialog to confirm a non-SSL connection. This behavior looks correct to me.

In case you want to have an unattended control for adding new JMX connections from the command line, the `--openjmx` command would need to support defining username & password, together with the option to disable SSL check. Is that what you are asking for?

**Comment by thurka** [comment]
Old inactive issue, closing.
