### ISSUE TITLE
wrong Vm parameters

### ISSUE THREAD

**Issue by wirowka** [oracle/visualvm#24]
we observed strange behaviour which caused serious issue on our site.
We configured few VMs in visualVM on Windows, we managed to connect and work with them for a long time. Recently we had to install fixpack of the products behind our VMs in visualVM.
What I did:
1. started visualVM
2. stopped the product (VM), installed fixpack, started the VM   <-- here heap size was accidentally changed
3. connected to the VM using visualVM (already started in the step 1)
4. visualVM after opening VM showed old heap size which was set before step 2 

This leads us into suspicion that maybe visualVM connects to all configured VMs during starting and gathers VM parameters. Does it work like that?
On our site the heap size was changed from 4GB go 2GB and caused major outage.

Thanks in advance for checking/commenting

**Comment by jisedlac** [comment]
What kind of application are you monitoring using the VisualVM? I assume it's a remote application using JMX connection - please confirm.

Currently when a JMX-connected application terminates, its window has to be closed in VisualVM and the connection node removed & added again or VisualVM has to be restarted in order to connect to the new application. Otherwise you still see data for the old (terminated) process - connection name and pid at the top of the view is gray.

This is a know annoyance and we're going to address it in some of the future VisualVM releases.

**Comment by wirowka** [comment]
Correct, I confirm.
The problem is that VisualVM connects to all defined Java processes and retrieves the parameters without explicitly opening the JVMs - this is totally misleading! Why you are doing it this way?

**Comment by jisedlac** [comment]
VisualVM opens the connections for several reasons:
  - to check whether the process is alive
  - to read process ID
  - to read additional process information for resolving customized display name

**Comment by wirowka** [comment]
All clear, but why VisualVM does some actions without explicitly opening VM? For egzample, in Oracle SQL Developer (just a sample), if you configure serveral DBs, no action will be done during the process startup. You have to explicitly connect to a DB to retrieve parameters and start working with the DB. 
Whereas VisualVM during it's boottime connects to processes, gathers startup parameters  and keeps them until VisualVM closure - without **any** user action, why? 
User (like we are) expect that when we click "Open" we connect to VM and retrieve the current and up2date parameters, instead we got parameters which were collected during VisualVM boot time (can be serveral hours ago) and the data displayed can be not up2date. This can cause major outage - like in our case. Why it is designed like that? What is the benefit of connecting to VMs and collecting data during boot?

**Comment by jisedlac** [comment]
VisualVM is designed this way, it's a different tool for different purposes and use cases. Again, when adding a new JMX connection, VisualVM reads these data:

  - tries to connect to the process - to verify whether the connection string is correct and there's no networking problem, otherwise you wouldn't realize you made a typo for example
  - process ID - will stay up to date, doesn't change
  - startup parameters - will stay up to date, don't change

The other data are being collected only after you open the application in VisualVM and are always up to date as well.

As I've described in the first comment, you've been presented obsolete data for the terminated process because you didn't relaunch VisualVM or re/created the JMX connection after restarting the process, which is a known usability annoyance to be addressed yet.
