### ISSUE TITLE
JavaFrameGCRoot.getThreadGCRoot() can be much faster

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#336]
Slow computation of JavaFrameGCRoot.getThreadGCRoot() for huge number of threads (>100.000) was fixed in GH-309. However when using `TreeMap` instead of `LongHashMap`  the `JavaFrameGCRoot.getThreadGCRoot()` is roughly 20x faster on the test case with 400.000 threads.

**Comment by thurka** [comment]
It turns out that the `LongHashMap` has a large number of hash collisions in situation when `keys` are lower number of keys. The keys are `thread serial number' which are numbered sequentially. The high number of collisions can be fixed by this change:
```diff
diff --git a/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofGCRoots.java b/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofGCRoots.java
index 2e08db888..89fbd8264 100644
--- a/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofGCRoots.java
+++ b/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofGCRoots.java
@@ -99,11 +99,11 @@ class HprofGCRoots {
                     GCRoot gcRoot = roots.get(i);
                     if (gcRoot instanceof ThreadObjectHprofGCRoot) {
                         ThreadObjectHprofGCRoot threadObjGC = (ThreadObjectHprofGCRoot) gcRoot;
-                        threadSerialMap.put(threadObjGC.getThreadSerialNumber(), i);
+                        threadSerialMap.put(threadObjGC.getThreadSerialNumber()*124193L, i);
                     }
                 }
             }
-            int threadIndex = (int)threadSerialMap.get(threadSerialNumber);
+            int threadIndex = (int)threadSerialMap.get(threadSerialNumber*124193L);
 
             if (threadIndex != -1) {
                 return (ThreadObjectGCRoot)roots.get(threadIndex);
```

**Comment by thurka** [comment]
Better fix - replace `LongHashMap` with int array.
```java
 int[] threadSerialMap = int[rootThreadsCount];
 ...
 threadSerialMap[threadObjGC.getThreadSerialNumber(), i];
```
this is fast and uses significantly less memory than `LongHashMap`.

**Comment by JaroslavTulach** [comment]
I was wondering why the `LongHashMap` is so slower? I thought it is backed by mmapped file, originally. At the end it is just a wrong hash function!

> It turns out that the `LongHashMap` has a large number of hash collisions in situation when `keys` are lower than number of keys. 

```java
    private static int hash(long x, int length) {
        int h = (int)(x ^ (x >>> 32)); // OK, this just turns a long into int using all its bits
        h ^= (h >>> 20) ^ (h >>> 12); // what a kind of magic can be found on this and next line!
        h ^= (h >>> 7) ^ (h >>> 4);  // let's assume it is correct - it might.
        return (h) & (length - 2); // However this cannot be right!
    }
```
To guarantee [uniform distribution](https://en.wikipedia.org/wiki/Discrete_uniform_distribution) I would expect the last line to be `h % (length - 2)`.  Using `&` instead of `%` is wrong unless `length` is guaranteed to be `2^n + 1` e.g. `length - 2 = 2^n - 1` e.g. all bits set. In such case the result of `&` and `%` would be identical. But one really wants to get the reminder of division, so better to use `%` just for clarity.

After spending few years along the compiler guys, I find this kind of shift right, xor & co. tricks a bit unnecessary - good compiler will convert the computation into something effective on its own. It's more important to get the [uniform distribution](https://en.wikipedia.org/wiki/Discrete_uniform_distribution) right as collisions seem way more costly than a few `int` operations.

**Comment by thurka** [comment]
Fixed in master.
