### ISSUE TITLE
Upgrade NetBeans Platform to 19

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#526]
VisualVM is currently built on NetBeans Platform 14. It would be useful to upgrade it to the latest NetBeans Platform.

**Comment by thurka** [comment]
Can you please point me to the VisualVM modules that are built with pack200? Thanks.

**Comment by jmborer** [comment]
Initially, we compiled VisualVM 1.4.2 with Java 8 to generate its NMBs. Those are Pack200.

We then reuse the graphs in our application that was based as well on Java 8 and NB 12.4. We had to publish them on our internal artifactory since only VisualVM 1.3.9 (or something like this) is the latest version available on internet (https://mvnrepository.com/artifact/com.sun.tools.visualvm.api/com-sun-tools-visualvm-core/RELEASE139). The later is anyway no longer available anyway. Maybe you know a more recent location for those Maven artifacts...

Now that we migration to NB 19 and finally Java 11, we need to recompile the latest VisualVM migrated on NBP 19 to have a common ground.
In the mean time, we try to see if the NBMs generate from VisualVM 1.4.2 would still work, but those use Pack200.

**Comment by thurka** [comment]
> we compiled VisualVM 1.4.2 with Java 8 to generate its NMBs. 

VisualVM 1.4.2 is 5 years old. Try to use something more recent.

> we need to recompile the latest VisualVM migrated

I don't think you need to recompile VisualVM, unless you need some modifications to VisualVM code.

> Maybe you know a more recent location for those Maven artifacts.

Are you looking for VisualVM maven arfifacts? Since VisualVM 2.1 they are available on [maven central](https://search.maven.org/search?q=visualvm). https://repo1.maven.org/maven2/org/graalvm/visualvm/

BTW: We are off-topic here, if you have more question please use our [feedback email address](https://visualvm.github.io/feedback.html).

**Comment by thurka** [comment]
Done in master.
