### ISSUE TITLE
VSCode Extension - JDK Path with Spaces not working

### ISSUE THREAD

**Issue by ninelore** [oracle/visualvm#572]
**Describe the bug**
The JDK Path, no matter if detected or explicitly set, doesnt seem to work correctly. Ive also tried with and without surrounding quotation marks.

**To Reproduce**
1. Have JDK in a Path with spaces (e.g. C:\Program FIles)
2. try to start VisualVM from the VSCode extension (the "play" icon)
3. If yes is pressed:
  - if jdkpath is set in visualvm.conf VisualVM will start and instantly crash. (it will start normally if started independently via the exe)
  - if its not set it will error with jdk not found

**Expected behavior**
VisualVM starting without error

**VisualVM log**
n/a

**Screenshots**
![image](https://github.com/oracle/visualvm/assets/21343557/efe64967-3551-4682-bee6-492f8a2cc148)

**Desktop (please complete the following information):**
 - OS: Win 11
 - JDK version: Eclipse Adoptium 21.0.3.9-hotspot

**Additional context**
n/a

LMK if i missed to provide any other info. thanks

**Comment by jisedlac** [comment]
Thank you for the report! I was able to reproduce the problem. Obviously caused by trying to run VisualVM using Java installed in a path containing spaces.

By default, the extension always starts VisualVM with the `--jdkhome` parameter. This means that even if the `visualvm_jdkhome` property is defined correctly in `visualvm.conf`, and VisualVM runs fine when started externally using `.exe`, it fails to start from within the VS Code.

Until fixed, the workaround is to unselect the Settings | Extensions | VisualVM | Use JDK Path for VisualVM option, or manually add `"visualvm.startup.useJdkPathForVisualvm": false` to `settings.json`. This will allow VisualVM to run using the JDK defined in `visualvm.conf`.

**Comment by jisedlac** [comment]
Fixed.
