### ISSUE TITLE
add zoom buttons so graphs don't always get compressed

### ISSUE THREAD

**Issue by danielnaber** [oracle/visualvm#94]
The longer data is collected, the more the graph gets compressed. It would be nice to have a UI like this, where you can select the time span you'd like to look at from "1h" to "All" (screen shot taken at satstuscake.com):

![zoom-buttons](https://user-images.githubusercontent.com/857004/41679585-fd27f88c-74ce-11e8-947e-5b04a130b92a.png)

**Comment by jisedlac** [comment]
The current approach has been selected because of performance and memory reasons. The graph always displays the full range (defined in Tools | Options | General | Charts Cache - 60 minutes by default) and throws away the older values.

If you need to collect the values for a longer time period and/or zoom the data, you should use the Tracer plugin - Monitor Probes. Alternatively you can increase the Charts Cache value and eventually take an Application Snapshot which allows you to zoom the graphs using buttons/mouse wheel.
